name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code into live folder
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          ls
          cd ~/actions-runner/_work/juneau_studio_portfolio/juneau_studio_portfolio &&
          ls &&
          echo $PWD
          whoami &&
          ls -ld . &&
          ls -ld node_modules &&
          ls -ld node_modules/.bin &&
          npm install

      - name: Fix permissions (if needed)
        run: chmod -R +x node_modules/.bin

      - name: Build project
        working-directory: /home/kxtnluc/vassals/juneau_studio_portfolio
        run: npx vite build

      - name: Deploy build to live directory
        run: |
          rsync -av --delete ./build/ /home/kxtnluc/vassals/juneau_studio_portfolio/
        # Replace ./build/ with your actual SvelteKit build output folder if different

      - name: Restart Nginx
        run: sudo systemctl restart nginx
