name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # or [self-hosted, linux, x64] if you prefer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Pull and build on server
        run: |
          cd vassals/juneau_studio_portfolio &&
          git pull origin main &&
          npm install &&
          npm run build &&
          sudo systemctl restart nginx

      - name: Install and Build
        run: |
          npm install &&
          npm run build

      - name: Restart Nginx
        run: sudo systemctl restart nginx
