name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code into runners folder
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          ls
          cd ~/actions-runner/_work/juneau_studio_portfolio/juneau_studio_portfolio &&
          ls &&
          echo $PWD
          whoami &&
          npm install &&
          ls -ld . &&
          ls -ld node_modules &&
          ls -ld node_modules/.bin

      - name: Fix permissions (if needed)
        run: |
          chmod -R +x node_modules/.bin &&
          chmod +x node_modules/vite/bin/vite.js

      - name: Build project
        run: node node_modules/vite/bin/vite.js build

      - name: Copy, Sync, and Move Around
        run: |
          rsync -av --delete ./build/ /home/kxtnluc/vassals/juneaustudio.com/build
        # Replace ./build/ with your actual SvelteKit build output folder if different

      - name: Restart Nginx and Pm2
        run: |
          sudo systemctl restart nginx
          pm2 restart juneaustudio
